version: '2'

services:
  drupal:
    image: drupal
    volumes:
      - drupal-modules:/var/www/html/modules:rw
      - drupal-profiles:/var/www/html/profiles:rw
      - drupal-sites:/var/www/html/sites:rw
      - drupal-themes:/var/www/html/themes:rw
    ports:
      - '8080:80'
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    environment: 
      - POSTGRES_PASSWORD=12345678
volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
    pgdata:
    
